### ISSUE TITLE
No need to send `pong` messages

### ISSUE THREAD

**Issue by an-tao** [moneroexamples/generic-xmr-scanner#1]
https://github.com/moneroexamples/generic-xmr-scanner/blob/d81b9cd0d5f915d8585ae3ad8bc5a09b6d519db9/src/controllers/SearchCtrl.cpp#L109-L113
You don't need to send pong messages in the application because pong messages are sent automatically by drogon as responses to ping messages.
https://github.com/an-tao/drogon/blob/01916a324aa172e9fede3c7833adf907f2df312a/lib/src/WebSocketConnectionImpl.h#L96-L100

**Comment by moneroexamples** [comment]
Thanks. Will remove that.

**Comment by moneroexamples** [comment]
Fixed. 

p.s.
Sorry for late reply. Just noticed the issue today.

**Comment by an-tao** [comment]
；-）
This seems to be a flaw on github, and I often notice new issues very late.
