### ISSUE TITLE
cmake build errors

### ISSUE THREAD

**Issue by SamsungGalaxyPlayer** [moneroexamples/generic-xmr-scanner#4]
I have attached my cmake log files after it failed. Let me know what other information you need.

[CMakeError.log](https://github.com/moneroexamples/generic-xmr-scanner/files/3264323/CMakeError.log)
[CMakeOutput.log](https://github.com/moneroexamples/generic-xmr-scanner/files/3264324/CMakeOutput.log)

**Comment by ArqTras** [comment]
Check again all libs needed to install provided on readme for coin and this repo

**Comment by moneroexamples** [comment]
Oh. Just now noticed this issue. Sorry for late reply. Github notification system is "strange" at best.

Does the issue is still relevant?

**Comment by ArqTras** [comment]
terminate called after throwing an instance of 'std::bad_any_cast'
  what():  bad any_cast
Still trying :D

**Comment by moneroexamples** [comment]
Still work in progress. But getting there.

You can check `add_config` branch: https://github.com/moneroexamples/generic-xmr-scanner/tree/add_config

Some of these type conversion bugs could have been fixed there. If not, do you have more info when it happens?

**Comment by ArqTras** [comment]
My error was caused by indicating the directory on the mounted disk, after connecting to the default directory the problem does not occur

**Comment by moneroexamples** [comment]
I think the issue can be closed now.
