### ISSUE TITLE
update drogon

### ISSUE THREAD

**Issue by an-tao** [moneroexamples/generic-xmr-scanner#7]
After update drogon to the latest version, you could remove the **FindDrogon.cmake**, **FindJsoncpp.cmake** from your project, and add drogon by some stuff like follows:
```
add_subdirectory(drogon)
set(Drogon_DIR ${PROJECT_BINARY_DIR}/drogon)
FIND_PACKAGE(Drogon CONFIG REQUIRED NO_DEFAULT_PATH)
include_directories(${DROGON_INCLUDE_DIRS})
link_libraries(${DROGON_LIBRARIES})
```
Drogon creates the DrogonConfig.cmake file for this.

**Comment by moneroexamples** [comment]
Thanks. Will look into it.

**Comment by moneroexamples** [comment]
Unfortunately, this is old style cmake. I prefer to use modern style cmake in my projects whenever I can.  

p.s.
Adapting modern cmake could also be a potential enhancement for drogon. It uses modern C++ (C++14 and up), so using modern cmake  seems as a natural progression:-).

**Comment by an-tao** [comment]
I'm sorry, I don't know much about cmake. I'll learn modern style cmake.
Can you give me some links about it? 
Or if you could make a PR for it(If it's not a big work), I would appreciate it very much.
Thank you for your reminder.

**Comment by moneroexamples** [comment]
These are good starting vids on modern cmake. 

https://www.youtube.com/watch?v=y7ndUhdQuU8
https://www.youtube.com/watch?v=eC9-iRN2b04

**Comment by an-tao** [comment]
Thank you very much!
